import 'package:dio/dio.dart';
import 'dart:io';
import 'dart:async';
import 'dart:convert';
import './httpHeaders.dart';
//  BaseOptions options = new BaseOptions(
//     baseUrl: "http://yapi.demo.qunar.com/mock/98814/flutter-learn/",
//     connectTimeout:5000,
//     receiveTimeout:3000,
//     contentType: Headers.formUrlEncodedContentType,
//     headers: httpHeaders
//   );

//   Dio dio = new Dio(options);
   
class Api {
  // var _dio = Dio();
  // static Dio _dio = new Dio();
  static Dio _dio;
  
  static void init() {
     _dio = Dio()
      ..options.baseUrl = "http://yapi.demo.qunar.com/mock/98814/flutter-learn/"
      ..options.connectTimeout = 5000 //5s
      ..options.receiveTimeout = 5000
      ..options.validateStatus = (int status) {
        return status > 0;
      }
      ..options.headers = {
        HttpHeaders.userAgentHeader: 'dio',
        'contentType': Headers.formUrlEncodedContentType,
        'x-access-token': 'zhang'
      };

    _dio.interceptors
    ..add(InterceptorsWrapper(
      onRequest:(RequestOptions options) async {
      // 在请求被发送之前做一些事情
      print(options.headers);
      _dio.interceptors.requestLock.lock();
      _dio.interceptors.requestLock.unlock();
      return options; //continue
      // 如果你想完成请求并返回一些自定义数据，可以返回一个`Response`对象或返回`dio.resolve(data)`。
      // 这样请求将会被终止，上层then会被调用，then中返回的数据将是你的自定义数据data.
      //
      // 如果你想终止请求并触发一个错误,你可以返回一个`DioError`对象，或返回`dio.reject(errMsg)`，
      // 这样请求将被中止并触发异常，上层catchError会被调用。
      },
      onResponse:(Response response) async {
      // 在返回响应数据之前做一些预处理
      return response; // continue
      },
      onError: (DioError e) async {
        // 当请求失败时做一些预处理
      return e;//continue
      }
    ))
    ..add(LogInterceptor(responseBody: false)); //O
  }


  static final _fetchTypes = <String, Function>{
    'post': _dio.post,
    'put': _dio.put,
    'patch': _dio.patch,
    'delete': _dio.delete,
    'head': _dio.head,
  };

  static Future<dynamic> get(url, {Map<String, dynamic> data}) async {
    return await _fetch('get', url, data);
  }

  static Future<dynamic> post(url, {Map<String, dynamic> data}) async {
    return await _fetch('post', url, data);
  }


 
  static Future<dynamic> _fetch(method, url, data) async {
    Api.init();
    try {
      final Response response = method == "get"
        ? await _dio.get(url, queryParameters: data)
        : await _fetchTypes[method](url, data: data);
        if(response.statusCode == 200){
          return response.data; 
        }else{
          Data res = Data.fromJson({});
          return res;
        }
    } catch (e) {
      print('错误');
      print(e);
      final error = (e is DioError
          && e.response != null
          && e.response.statusCode == 403)
        ? e.response.data
        : {"message": "服务器网络繁忙，请稍后再试", "status_code": 1001};

      // showTip(error['message']);

      throw error;
    }
  }


}


class Autogenerated {
  int status;
  Data data;

  Autogenerated({this.status, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    data = json['data'] != null ? new Data.fromJson(json['data']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['status'] = this.status;
    if (this.data != null) {
      data['data'] = this.data.toJson();
    }
    return data;
  }
}

class Data {
  int total;
  List<MyList> list;

  Data({this.total, this.list});

  Data.fromJson(Map<String, dynamic> json) {
    total = json['total'];
    if (json['list'] != null) {
      list = new List<MyList>();
      json['list'].forEach((v) {
        list.add(new MyList.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['total'] = this.total;
    if (this.list != null) {
      data['list'] = this.list.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class MyList {
  String name;
  int id;

  MyList({this.name, this.id});

  MyList.fromJson(Map<String, dynamic> json) {
    name = json['name'];
    id = json['id'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['name'] = this.name;
    data['id'] = this.id;
    return data;
  }
}